import { Property } from "../lib/types";

const IMG = {
  exterior1:
    "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80&auto=format&fit=crop",
  exterior2:
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80&auto=format&fit=crop",
  exterior3:
    "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80&auto=format&fit=crop",
  exterior4:
    "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80&auto=format&fit=crop",
  exterior5:
    "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&q=80&auto=format&fit=crop",
  exterior6:
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80&auto=format&fit=crop",
  exterior7:
    "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=80&auto=format&fit=crop",
  exterior8:
    "https://images.unsplash.com/photo-1565402170291-8491f14678db?w=1200&q=80&auto=format&fit=crop",
  exterior9:
    "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80&auto=format&fit=crop",
  living1:
    "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1200&q=80&auto=format&fit=crop",
  living2:
    "https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=1200&q=80&auto=format&fit=crop",
  kitchen1:
    "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=80&auto=format&fit=crop",
  apartment1:
    "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80&auto=format&fit=crop",
  apartment2:
    "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80&auto=format&fit=crop",
};

export const properties: Property[] = [
  {
    id: "1",
    slug: "the-ashford-residence-bsd",
    name: "The Ashford Residence",
    type: "rumah",
    status: "tersedia",
    location: "BSD City",
    city: "Tangerang Selatan",
    price: 4_250_000_000,
    bedrooms: 4,
    bathrooms: 3,
    landArea: 200,
    buildingArea: 240,
    images: [IMG.exterior1, IMG.living1, IMG.kitchen1],
    description:
      "Hunian mewah dua lantai dengan desain arsitektur kontemporer di jantung BSD City. Dilengkapi kolam renang privat, taman belakang, dan smart home system. Lingkungan cluster eksklusif dengan keamanan 24 jam.",
    facilities: [
      "Kolam renang privat",
      "Smart home system",
      "Carport 2 mobil",
      "Taman belakang",
      "Keamanan 24 jam",
      "One gate system",
    ],
    featured: true,
  },
  {
    id: "2",
    slug: "skyline-suites-sudirman",
    name: "Skyline Suites",
    type: "apartemen",
    status: "promo",
    location: "Sudirman",
    city: "Jakarta Selatan",
    price: 2_800_000_000,
    bedrooms: 3,
    bathrooms: 2,
    landArea: 0,
    buildingArea: 120,
    images: [IMG.apartment1, IMG.apartment2, IMG.living2],
    description:
      "Apartemen premium di lantai tinggi dengan panorama skyline Jakarta. Akses langsung ke pusat bisnis Sudirman, dilengkapi fasilitas sky lounge, infinity pool, dan private lift lobby.",
    facilities: [
      "Infinity pool",
      "Sky lounge",
      "Private lift lobby",
      "Fitness center",
      "Concierge 24 jam",
      "Smart parking",
    ],
    featured: true,
  },
  {
    id: "3",
    slug: "grand-pavilion-dago",
    name: "Grand Pavilion Dago",
    type: "rumah",
    status: "tersedia",
    location: "Dago Atas",
    city: "Bandung",
    price: 5_900_000_000,
    bedrooms: 5,
    bathrooms: 4,
    landArea: 350,
    buildingArea: 300,
    images: [IMG.exterior2, IMG.exterior9, IMG.living1],
    description:
      "Vila mewah bergaya modern tropis dengan pemandangan pegunungan Dago. Udara sejuk sepanjang tahun, desain terbuka dengan banyak bukaan cahaya alami, dan area rooftop untuk bersantai.",
    facilities: [
      "Rooftop lounge",
      "View pegunungan",
      "Home theater",
      "Wine cellar",
      "Carport 3 mobil",
      "Taman tropis",
    ],
    featured: true,
  },
  {
    id: "4",
    slug: "riverside-commercial-loft",
    name: "Riverside Commercial Loft",
    type: "ruko",
    status: "tersedia",
    location: "Kelapa Gading",
    city: "Jakarta Utara",
    price: 3_100_000_000,
    bedrooms: 0,
    bathrooms: 2,
    landArea: 90,
    buildingArea: 220,
    images: [IMG.exterior7, IMG.exterior4, IMG.living2],
    description:
      "Ruko tiga lantai di kawasan komersial strategis Kelapa Gading, cocok untuk kantor, showroom, atau F&B. Akses jalan utama dengan lalu lintas tinggi dan area parkir luas.",
    facilities: [
      "3 lantai",
      "Akses jalan utama",
      "Area parkir luas",
      "Listrik 10.000 VA",
      "Mezzanine",
      "Loading dock",
    ],
    featured: false,
  },
  {
    id: "5",
    slug: "villa-samudra-canggu",
    name: "Villa Samudra",
    type: "rumah",
    status: "promo",
    location: "Canggu",
    city: "Bali",
    price: 7_500_000_000,
    bedrooms: 4,
    bathrooms: 5,
    landArea: 400,
    buildingArea: 320,
    images: [IMG.exterior5, IMG.exterior1, IMG.kitchen1],
    description:
      "Vila tropis eksklusif beberapa menit dari pantai Canggu. Desain open-plan dengan kolam renang tepi taman, cocok untuk hunian pribadi maupun investasi sewa harian.",
    facilities: [
      "Kolam renang tepi taman",
      "Open-plan living",
      "5 menit ke pantai",
      "Outdoor kitchen",
      "Villa manager service",
      "Full furnished",
    ],
    featured: true,
  },
  {
    id: "6",
    slug: "the-meridian-tower-thamrin",
    name: "The Meridian Tower",
    type: "apartemen",
    status: "tersedia",
    location: "Thamrin",
    city: "Jakarta Pusat",
    price: 3_600_000_000,
    bedrooms: 2,
    bathrooms: 2,
    landArea: 0,
    buildingArea: 95,
    images: [IMG.apartment2, IMG.apartment1, IMG.living1],
    description:
      "Apartemen strategis di pusat kota Jakarta dengan akses langsung ke MRT dan pusat perbelanjaan. Ideal untuk profesional muda maupun investasi sewa jangka panjang.",
    facilities: [
      "Akses langsung MRT",
      "Rooftop pool",
      "Co-working space",
      "24-hour security",
      "Retail podium",
      "EV charging station",
    ],
    featured: false,
  },
  {
    id: "7",
    slug: "cluster-mahogany-alam-sutera",
    name: "Cluster Mahogany",
    type: "rumah",
    status: "tersedia",
    location: "Alam Sutera",
    city: "Tangerang",
    price: 3_450_000_000,
    bedrooms: 3,
    bathrooms: 3,
    landArea: 150,
    buildingArea: 180,
    images: [IMG.exterior3, IMG.exterior6, IMG.living2],
    description:
      "Hunian dua lantai bergaya modern minimalis dalam cluster asri di Alam Sutera. Dekat dengan sekolah internasional, mall, dan akses tol.",
    facilities: [
      "Cluster asri",
      "Dekat sekolah internasional",
      "Taman bermain anak",
      "Jogging track",
      "Keamanan 24 jam",
      "CCTV terintegrasi",
    ],
    featured: false,
  },
  {
    id: "8",
    slug: "harborview-residence-pik",
    name: "Harborview Residence",
    type: "rumah",
    status: "terjual",
    location: "Pantai Indah Kapuk",
    city: "Jakarta Utara",
    price: 8_900_000_000,
    bedrooms: 5,
    bathrooms: 5,
    landArea: 300,
    buildingArea: 380,
    images: [IMG.exterior8, IMG.exterior2, IMG.kitchen1],
    description:
      "Hunian waterfront eksklusif dengan pemandangan laguna PIK. Desain arsitektur kontemporer tiga lantai dengan private dock dan rooftop infinity pool.",
    facilities: [
      "Private dock",
      "Rooftop infinity pool",
      "View laguna",
      "Lift pribadi",
      "Smart home system",
      "Garasi 4 mobil",
    ],
    featured: false,
  },
  {
    id: "9",
    slug: "ruko-platinum-boulevard-surabaya",
    name: "Ruko Platinum Boulevard",
    type: "ruko",
    status: "promo",
    location: "Citraland",
    city: "Surabaya",
    price: 2_650_000_000,
    bedrooms: 0,
    bathrooms: 2,
    landArea: 80,
    buildingArea: 160,
    images: [IMG.exterior4, IMG.exterior7, IMG.living2],
    description:
      "Ruko dua lantai di kawasan boulevard utama Citraland, sangat cocok untuk usaha retail, klinik, atau kantor cabang dengan visibilitas tinggi.",
    facilities: [
      "Visibilitas tinggi",
      "2 lantai",
      "Area parkir depan",
      "Listrik 7.700 VA",
      "Dekat pusat bisnis",
      "Bebas banjir",
    ],
    featured: true,
  },
];
